"""Initial schema: models, PostGIS geometry, monthly-partitioned observation.

Revision ID: 0001
Revises:
Create Date: 2026-08-24

Everything ``cascade_core.models.Base.metadata`` defines (docs/DOMAIN_MODEL.md at spike
scope), plus the PostgreSQL-only surface:

- ``CREATE EXTENSION IF NOT EXISTS postgis`` (PG 18.x + PostGIS 3.6.x per ADR-0013 evidence).
- ``basin_geometry`` — (basin_id, lod) -> geometry(MULTIPOLYGON, 4326) NOT NULL, GiST-indexed;
  display/analysis polygons per LOD, regenerable from tests/fixtures/geo seed GeoJSON.
- Nullable ``geom geometry(POINT, 4326)`` on ``station`` and ``forecast_point``, GiST-indexed.
  The plain lon/lat columns stay as-is and remain the seed's source of truth. These two
  columns are deliberately absent from the ORM metadata (plain SQLite cannot hold them); the
  registry ``cascade_core.models.PG_ONLY_GEOMETRY_COLUMNS`` + env.py ``include_object`` keep
  autogenerate honest about them.
- ``observation`` is partitioned by RANGE (valid_time), monthly. Consequences:
  - primary key becomes the composite (id, valid_time) — PostgreSQL requires the partition
    key inside it — while ``id`` keeps identity/autoincrement semantics via GENERATED BY
    DEFAULT AS IDENTITY (identity on a partitioned parent needs PostgreSQL >= 17);
  - the model's natural-key unique constraint already contains ``valid_time``, so it is legal
    on the parent and becomes the partition-local unique index on every partition;
  - ``revision_of`` carries no foreign key here: a FK must target a unique constraint, and on
    the partitioned table only (id, valid_time) is unique. The column stays; the revision
    link is application-maintained (append-only doctrine, docs/DATA_DOCTRINE.md §8).

Partition management (ADR-0013): pg_partman is the intended manager on Neon, where the
extension is available; ``cascade_ensure_month_partitions(from_month, to_month)`` below is
the fallback where the extension is absent (local docker PostGIS, CI scratch databases).
This migration premakes partitions 2025-11 through 2027-01 (Event Zero window through a year
of headroom) plus a DEFAULT partition, so an out-of-range valid_time can never lose a row.
Note: with a DEFAULT partition in place, creating a later partition requires the default to
hold no rows in the new range — keep premaking ahead of ingestion.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ENSURE_PARTITIONS_FN = """
CREATE OR REPLACE FUNCTION cascade_ensure_month_partitions(from_month date, to_month date)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    m date := date_trunc('month', from_month)::date;
    last_month date := date_trunc('month', to_month)::date;
    part_name text;
    created integer := 0;
BEGIN
    WHILE m <= last_month LOOP
        part_name := format('observation_y%sm%s', to_char(m, 'YYYY'), to_char(m, 'MM'));
        IF to_regclass(part_name) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF observation FOR VALUES FROM (%L) TO (%L)',
                part_name, m, (m + interval '1 month')::date
            );
            created := created + 1;
        END IF;
        m := (m + interval '1 month')::date;
    END LOOP;
    RETURN created;
END;
$$
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "basin",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("regulation_class", sa.String(), nullable=False),
        sa.Column("outlet_fp_id", sa.String(), nullable=True),
        sa.Column("huc8", sa.JSON(), nullable=False),
        sa.Column("centroid", sa.JSON(), nullable=True),
        sa.Column("bbox", sa.JSON(), nullable=True),
        sa.Column("geometry_ref", sa.String(), nullable=True),
        sa.Column("regulated_by", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "data_source",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("authority", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("docs_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "station",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agency", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("basin_id", sa.String(), sa.ForeignKey("basin.id"), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("vertical_datum", sa.String(), nullable=True),
        sa.Column("time_zone", sa.String(), nullable=True),
        sa.Column("geom", Geometry(geometry_type="POINT", srid=4326, spatial_index=False), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_station_geom", "station", ["geom"], postgresql_using="gist")

    op.create_table(
        "forecast_point",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("lid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("station_id", sa.String(), sa.ForeignKey("station.id"), nullable=True),
        sa.Column("basin_id", sa.String(), sa.ForeignKey("basin.id"), nullable=True),
        sa.Column("upstream_lids", sa.JSON(), nullable=False),
        sa.Column("downstream_lids", sa.JSON(), nullable=False),
        sa.Column("reach_id", sa.String(), nullable=True),
        sa.Column("datums", sa.JSON(), nullable=False),
        sa.Column("rfc", sa.String(), nullable=True),
        sa.Column("wfo", sa.String(), nullable=True),
        sa.Column("in_service", sa.Boolean(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("geom", Geometry(geometry_type="POINT", srid=4326, spatial_index=False), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lid"),
    )
    op.create_index("ix_forecast_point_geom", "forecast_point", ["geom"], postgresql_using="gist")

    op.create_table(
        "basin_geometry",
        sa.Column("basin_id", sa.String(), sa.ForeignKey("basin.id"), nullable=False),
        sa.Column("lod", sa.String(), nullable=False),
        sa.Column("geom", Geometry(geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False), nullable=False),
        sa.CheckConstraint("lod IN ('state', 'basin')", name="ck_basin_geometry_lod"),
        sa.PrimaryKeyConstraint("basin_id", "lod"),
    )
    op.create_index("ix_basin_geometry_geom", "basin_geometry", ["geom"], postgresql_using="gist")

    op.create_table(
        "source_product",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), sa.ForeignKey("data_source.id"), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("expected_cadence_seconds", sa.Integer(), nullable=False),
        sa.Column("grace_seconds", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "raw_artifact",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), sa.ForeignKey("source_product.id"), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("request_url", sa.String(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_raw_artifact_sha256", "raw_artifact", ["sha256"])

    op.create_table(
        "observation",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("station_id", sa.String(), sa.ForeignKey("station.id"), nullable=False),
        sa.Column("product_id", sa.String(), sa.ForeignKey("source_product.id"), nullable=False),
        sa.Column("variable", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("datum", sa.String(), nullable=True),
        sa.Column("valid_time", sa.DateTime(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("quality", sa.JSON(), nullable=False),
        sa.Column("qualifier_raw", sa.String(), nullable=True),
        sa.Column("revision_of", sa.BigInteger(), nullable=True),  # no FK: see module docstring
        sa.Column("revision_seq", sa.Integer(), nullable=False),
        sa.Column("raw_artifact_id", sa.Integer(), sa.ForeignKey("raw_artifact.id"), nullable=False),
        sa.PrimaryKeyConstraint("id", "valid_time"),
        sa.UniqueConstraint(
            "product_id", "station_id", "variable", "valid_time", "revision_seq",
            name="uq_observation_revision",
        ),
        postgresql_partition_by="RANGE (valid_time)",
    )
    # Partitioned indexes on the parent: every existing and future partition inherits them.
    op.create_index("ix_observation_station_id", "observation", ["station_id"])
    op.create_index("ix_observation_valid_time", "observation", ["valid_time"])
    op.create_index("ix_observation_available_at", "observation", ["available_at"])

    op.execute(_ENSURE_PARTITIONS_FN)
    op.execute("SELECT cascade_ensure_month_partitions(DATE '2025-11-01', DATE '2027-01-01')")
    op.execute("CREATE TABLE observation_default PARTITION OF observation DEFAULT")

    op.create_table(
        "forecast_run",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("product_id", sa.String(), sa.ForeignKey("source_product.id"), nullable=False),
        sa.Column("fp_id", sa.String(), sa.ForeignKey("forecast_point.id"), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("primary_variable", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("stage_unit", sa.String(), nullable=True),
        sa.Column("flow_unit", sa.String(), nullable=True),
        sa.Column("datum", sa.String(), nullable=True),
        sa.Column("raw_artifact_id", sa.Integer(), sa.ForeignKey("raw_artifact.id"), nullable=False),
        sa.Column("supersedes_run_id", sa.Integer(), sa.ForeignKey("forecast_run.id"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "fp_id", "issued_at", name="uq_forecast_run_issuance"),
    )
    op.create_index("ix_forecast_run_fp_id", "forecast_run", ["fp_id"])
    op.create_index("ix_forecast_run_available_at", "forecast_run", ["available_at"])

    op.create_table(
        "forecast_value",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("run_id", sa.Integer(), sa.ForeignKey("forecast_run.id"), nullable=False),
        sa.Column("valid_time", sa.DateTime(), nullable=False),
        sa.Column("stage", sa.Float(), nullable=True),
        sa.Column("flow", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "valid_time", name="uq_forecast_value_run_valid_time"),
    )
    op.create_index("ix_forecast_value_run_id", "forecast_value", ["run_id"])

    op.create_table(
        "threshold",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("fp_id", sa.String(), sa.ForeignKey("forecast_point.id"), nullable=False),
        sa.Column("product_id", sa.String(), sa.ForeignKey("source_product.id"), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("basis", sa.String(), nullable=False),
        sa.Column("datum", sa.String(), nullable=True),
        sa.Column("source_kind", sa.String(), nullable=False),
        sa.Column("effective_from", sa.DateTime(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("raw_artifact_id", sa.Integer(), sa.ForeignKey("raw_artifact.id"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_threshold_fp_id", "threshold", ["fp_id"])
    op.create_index("ix_threshold_effective_from", "threshold", ["effective_from"])

    op.create_table(
        "job_run",
        sa.Column("id", sa.Integer(), sa.Identity(), nullable=False),
        sa.Column("job", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_run_job", "job_run", ["job"])


def downgrade() -> None:
    op.drop_table("job_run")
    op.drop_table("threshold")
    op.drop_table("forecast_value")
    op.drop_table("forecast_run")
    op.execute("DROP TABLE observation")  # dropping the partitioned parent drops its partitions
    op.execute("DROP FUNCTION IF EXISTS cascade_ensure_month_partitions(date, date)")
    op.drop_table("raw_artifact")
    op.drop_table("source_product")
    op.drop_table("basin_geometry")
    op.drop_table("forecast_point")
    op.drop_table("station")
    op.drop_table("data_source")
    op.drop_table("basin")
    # The postgis extension is left installed: it is shared infrastructure.
